# https://cloud.google.com/kubernetes-engine/docs/concepts/statefulset
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

# ❯ k get statefulset
# I0926 13:43:39.980489   75253 versioner.go:58] no Auth Provider found for name "gcp"
# W0926 13:43:40.108048   75253 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
# To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
# NAME   READY   AGE
# web    3/3     2m15s

# ❯ k get po -l app=nginx -o wide
# I0926 13:43:12.838343   75183 versioner.go:58] no Auth Provider found for name "gcp"
# W0926 13:43:12.886270   75183 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
# To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
# NAME    READY   STATUS    RESTARTS   AGE    IP          NODE                                                  NOMINATED NODE   READINESS GATES
# web-0   1/1     Running   0          107s   10.72.4.5   gke-tester-devops-gk-tester-devops-gk-39cb36e5-fklh   <none>           <none>
# web-1   1/1     Running   0          82s    10.72.6.6   gke-tester-devops-gk-tester-devops-gk-9d997730-ztc0   <none>           <none>
# web-2   1/1     Running   0          60s    10.72.7.3   gke-tester-devops-gk-tester-devops-gk-b9dd00db-57k1   <none>           <none>
