# https://cloud.google.com/kubernetes-engine/docs/concepts/service?hl=zh-TW
apiVersion: v1
kind: Service
metadata:
  name: my-np-service
spec:
  selector:
    app: products
    department: sales
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080